server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: 'practice-spring-boot-paging-lv3'
  profiles:
    active: local

  config:
    import: classpath:extra.yml

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  datasource:
    generate-unique-name: false
    driver-class-name: org.h2.Driver
    url: ${DB_URL:jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_UPPER=FALSE}
    username: ${DB_USER:sa}
    password: ${DB_PASS:}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:1}

  h2:
    console:
      enabled: true
      path: /h2-console


# 로그 설정
logging:
  config:
    classpath: logback.xml


management:
  endpoints:
    web:
      exposure:
        include: health, httptrace, info, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}    # Prometheus label name
